"""
Crossed product: M ⋊_α Z_n implementation and tests.

Mathematical setup:
- M: a von Neumann algebra acting on Hilbert space H
- alpha: an automorphism of M of period n (so α^n = identity on M)
- The crossed product M ⋊_α Z_n acts on H ⊗ C^n
- Generators:
  - pi(a) = a ⊗ P_0 + α(a) ⊗ P_1 + α^2(a) ⊗ P_2 + ... + α^{n-1}(a) ⊗ P_{n-1}
    where P_k is the projection onto |k> in C^n
  - U = I ⊗ S where S is the cyclic shift on C^n (S|k> = |k+1 mod n>)
- These satisfy the covariance relation: U pi(a) U^{-1} = pi(α(a))

The "Z_n" version is the natural finite-dim analog of M ⋊_α R, which requires
an infinite-dim clock. Taking n → infinity with appropriate scaling gives R.

For the CLPW application:
- M = CFT algebra (our finite-dim proxy)
- alpha = modular flow (discretized: one step = some fraction of 2π in imaginary time)
- n = number of discrete clock states
- The crossed product is the "observer-inclusive" algebra
"""

import numpy as np
from scipy.linalg import expm, logm
import sys
sys.path.insert(0, '/home/claude/vn_algebra')
from vnalgebra import (commutant, algebra_closure, is_cyclic_separating,
                       tomita_takesaki, modular_flow, algebra_type_finite_dim)


def crossed_product_Zn(algebra_basis, alpha_action, n, dim):
    """
    Construct M ⋊_α Z_n where alpha_action is a function mapping matrices to matrices
    (representing the automorphism alpha of order n).
    
    Returns:
      - generators of the crossed product algebra (acting on C^dim ⊗ C^n)
      - the shift unitary U
    """
    # Build pi(a) for each a in algebra_basis
    # pi(a) = sum_{k=0}^{n-1} alpha^k(a) ⊗ P_k
    # where P_k is |k><k| in C^n
    
    new_dim = dim * n
    crossed_basis = []
    
    # Need alpha_inverse to build pi(a) = sum_k alpha_{-k}(a) ⊗ |k><k|
    # (This is the correct sign convention for U pi(a) U^{-1} = pi(alpha(a)).)
    # Since we only have alpha and alpha^n = id, alpha_{-1} = alpha_{n-1}.
    
    for a in algebra_basis:
        # Compute all alpha_{-k}(a) for k = 0, ..., n-1
        # alpha_{-k}(a) = alpha_{n-k}(a) mod n
        alpha_powers_pos = [a]  # alpha^0, alpha^1, ..., alpha^{n-1}
        current = a
        for _ in range(n - 1):
            current = alpha_action(current)
            alpha_powers_pos.append(current)
        
        # alpha_{-k} = alpha_{n-k} mod n; for k=0 it's alpha^0 = id
        alpha_neg_powers = [alpha_powers_pos[(-k) % n] for k in range(n)]
        
        # Build pi(a) = sum_k alpha_{-k}(a) ⊗ |k><k|
        pi_a = np.zeros((new_dim, new_dim), dtype=complex)
        for k in range(n):
            P_k = np.zeros((n, n), dtype=complex)
            P_k[k, k] = 1.0
            pi_a += np.kron(alpha_neg_powers[k], P_k)
        
        crossed_basis.append(pi_a)
    
    # Shift operator S: |k> -> |k+1 mod n>
    S = np.zeros((n, n), dtype=complex)
    for k in range(n):
        S[(k + 1) % n, k] = 1.0
    
    U = np.kron(np.eye(dim), S)
    
    # The crossed product is generated by {pi(a) : a in M} ∪ {U}
    generators = crossed_basis + [U]
    
    return generators, U


def verify_covariance(algebra_basis, alpha_action, n, dim):
    """
    Verify that U pi(a) U^{-1} = pi(α(a)) on the crossed product.
    This is the defining relation.
    """
    generators, U = crossed_product_Zn(algebra_basis, alpha_action, n, dim)
    pi_basis = generators[:-1]  # everything except U
    
    U_inv = U.conj().T
    
    max_error = 0.0
    for i, a in enumerate(algebra_basis):
        alpha_a = alpha_action(a)
        # pi(alpha(a)) = sum_k alpha_{-k}(alpha(a)) ⊗ |k><k|
        #             = sum_k alpha_{1-k}(a) ⊗ |k><k|
        alpha_a_powers_pos = [alpha_a]
        current = alpha_a
        for _ in range(n - 1):
            current = alpha_action(current)
            alpha_a_powers_pos.append(current)
        
        alpha_a_neg_powers = [alpha_a_powers_pos[(-k) % n] for k in range(n)]
        
        pi_alpha_a = np.zeros((dim * n, dim * n), dtype=complex)
        for k in range(n):
            P_k = np.zeros((n, n), dtype=complex)
            P_k[k, k] = 1.0
            pi_alpha_a += np.kron(alpha_a_neg_powers[k], P_k)
        
        lhs = U @ pi_basis[i] @ U_inv
        error = np.linalg.norm(lhs - pi_alpha_a)
        max_error = max(max_error, error)
    
    return max_error


if __name__ == "__main__":
    print("="*70)
    print("CROSSED PRODUCT TEST: M ⋊__α_t} Z_n for a thermal state")
    print("="*70)
    
    dim = 4
    I_2 = np.eye(2, dtype=complex)
    sx = np.array([[0, 1], [1, 0]], dtype=complex)
    sz = np.array([[1, 0], [0, -1]], dtype=complex)
    
    generators_M = [np.kron(sx, I_2), np.kron(sz, I_2)]
    M = algebra_closure(generators_M, dim)
    print(f"\nM: operators A ⊗ I on C^4, dim(M) = {len(M)}")
    
    beta = 1.5
    Omega_TFD = np.zeros(4, dtype=complex)
    Omega_TFD[0] = np.exp(-beta/2)
    Omega_TFD[3] = np.exp(beta/2)
    Omega_TFD /= np.linalg.norm(Omega_TFD)
    
    tt = tomita_takesaki(M, Omega_TFD, dim)
    Delta = tt['Delta']
    print(f"Delta from Tomita-Takesaki: eigenvalues = {np.sort(np.linalg.eigvalsh((Delta+Delta.conj().T)/2))}")
    
    n = 4
    t_step = 2 * np.pi / (n * 2 * beta)
    print(f"\nDiscretized modular flow: n = {n}, t_step = {t_step:.4f}")
    
    def alpha(a, t=t_step, Delta=Delta):
        return modular_flow(Delta, a, t)
    
    test_a = generators_M[0]
    current = test_a.copy()
    for _ in range(n):
        current = alpha(current)
    
    id_error = np.linalg.norm(current - test_a)
    print(f"||alpha^n(sx otimes I) - sx otimes I|| = {id_error:.2e}")
    
    crossed_gens, U = crossed_product_Zn(M, alpha, n, dim)
    new_dim = dim * n
    print(f"\nCrossed product M rtimes Z_{n}: acts on C^{new_dim}")
    
    cov_err = verify_covariance(M, alpha, n, dim)
    print(f"  Covariance check: {cov_err:.2e}")
    
    M_crossed = algebra_closure(crossed_gens, new_dim)
    print(f"  dim(M rtimes Z_{n}) = {len(M_crossed)}")
    
    print("\nFinite-dim classification:")
    cls = algebra_type_finite_dim(M_crossed, new_dim)
    print(f"  {cls}")
    
    print("\n" + "="*60)
    print("CROSSED PRODUCT: works in finite dim Z_n case")
    print("="*60)
